### ISSUE TITLE
INTERACT

### ISSUE THREAD

**Issue by N1kollas** [scomans/MyPet#1469]
# Bug report

* [ ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. 
2.
...

## Expected behavior

_A clear and concise description of what you expected to happen._

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**What is the expected result?**

**What happens instead of that?**

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```

**Comment by xaw3ep** [comment]
q=                                                                                                                                                                                                                                                                                                                                        Gửi từ điện thoại thông minh BlackBerry 10.                                                                                                                                                                                                                Từ: N1kollasĐã gửi: 2:54 Thứ hai, ngày 24 tháng năm năm 2021Đến: scomans/MyPetTrả lời đến: scomans/MyPetCc: SubscribedChủ đề: Re: [scomans/MyPet] INTERACT (#1469)
Closed #1469.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/scomans/MyPet/issues/1469#event-4783675265",
"url": "https://github.com/scomans/MyPet/issues/1469#event-4783675265",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
